insert into state (id, name) values (null, 'PE')
insert into state (id, name) values (null, 'CE')
insert into state (id, name) values (null, 'RN')
insert into state (id, name) values (null, 'PB')
insert into state (id, name) values (null, 'MG')
insert into state (id, name) values (null, 'BA')
insert into state (id, name) values (null, 'SP')
insert into state (id, name) values (null, 'RJ')
insert into state (id, name) values (null, 'RS')
insert into state (id, name) values (null, 'PR')
insert into state (id, name) values (null, 'GO')
insert into state (id, name) values (null, 'DF')
insert into state (id, name) values (null, 'AL')

insert into city (id, name, state_id) values (null, 'Recife', 1)
insert into city (id, name, state_id) values (null, 'Fortaleza', 2)
insert into city (id, name, state_id) values (null, 'Natal', 3)
insert into city (id, name, state_id) values (null, 'João Pessoa', 4)
insert into city (id, name, state_id) values (null, 'Belo Horizonte', 5)
insert into city (id, name, state_id) values (null, 'Salvador', 6)
insert into city (id, name, state_id) values (null, 'São Paulo', 7)
insert into city (id, name, state_id) values (null, 'Rio de Janeiro', 8)
insert into city (id, name, state_id) values (null, 'Porto Alegre', 9)
insert into city (id, name, state_id) values (null, 'Curitiba', 10)
insert into city (id, name, state_id) values (null, 'Goiânia', 11)
insert into city (id, name, state_id) values (null, 'Brasília', 12)
insert into city (id, name, state_id) values (null, 'Maceió', 13)

insert into client (id, name, gender, birthday, city_id) values (null, 'Maria da Silva', 0, 'aced00057372000d6a6176612e74696d652e536572955d84ba1b2248b20c00007870770703000007c6010178', 1)
insert into client (id, name, gender, birthday, city_id) values (null, 'João de Souza', 1, null, 2)
