insert into city values(null, 'Recife')
insert into city values(null, 'Natal')
insert into city values(null, 'João Pessoa')
insert into city values(null, 'Belo Horizonte')
insert into city values(null, 'Salvador')
insert into city values(null, 'São Paulo')
insert into city values(null, 'Rio de Janeiro')
insert into city values(null, 'Porto Alegre')
insert into city values(null, 'Curitiba')
insert into city values(null, 'Goiânia')
insert into city values(null, 'Brasília')
insert into city values(null, 'Maceió')

insert into client (id, name, gender, birthday, city_id) values (null, 'Maria da Silva', 0, 'aced00057372000d6a6176612e74696d652e536572955d84ba1b2248b20c00007870770703000007c6010178', 1)
insert into client (id, name, gender, birthday, city_id) values (null, 'João de Souza', 1, null, 2)
